"""Public, Haiqu-independent contracts for Q-ErrorID."""

from .channels import (
    LOCAL_DAMPING_CONVENTION,
    QuantumChannel,
    build_channel,
    build_diagnostic_channel,
    generator_liouvillian,
    ideal_gate_channel,
    identity_channel,
    unitary_channel,
)
from .identifiability import (
    IdentifiabilityResult,
    analyze_identifiability,
    numerical_feature_jacobian,
    representative_parameters,
    select_protocol,
)
from .metrics import (
    choi_state_fidelity,
    error_strengths,
    heldout_observable_prediction_error,
    minimum_choi_eigenvalue,
    parameter_mae,
    parameter_rmse,
    relative_ptm_frobenius_error,
    trace_preservation_violation,
    unitarity,
)
from .parameters import (
    ChannelParameters,
    one_qubit_parameters,
    parameter_bounds,
    two_qubit_parameters,
)
from .protocols import (
    ChoiStateProtocol,
    PrepareMeasureProtocol,
    ReadoutConfusion,
    expectation_from_choi,
    extract_features,
    one_qubit_protocol,
    two_qubit_candidate_protocol,
    two_qubit_protocol,
)
from .representations import (
    channel_to_choi,
    channel_to_choi_state,
    channel_to_kraus,
    channel_to_liouville,
    channel_to_ptm,
    validate_channel,
)

__all__ = [
    "LOCAL_DAMPING_CONVENTION",
    "ChannelParameters",
    "ChoiStateProtocol",
    "IdentifiabilityResult",
    "PrepareMeasureProtocol",
    "QuantumChannel",
    "ReadoutConfusion",
    "analyze_identifiability",
    "build_channel",
    "build_diagnostic_channel",
    "channel_to_choi",
    "channel_to_choi_state",
    "channel_to_kraus",
    "channel_to_liouville",
    "channel_to_ptm",
    "choi_state_fidelity",
    "error_strengths",
    "expectation_from_choi",
    "extract_features",
    "generator_liouvillian",
    "heldout_observable_prediction_error",
    "ideal_gate_channel",
    "identity_channel",
    "minimum_choi_eigenvalue",
    "numerical_feature_jacobian",
    "one_qubit_parameters",
    "one_qubit_protocol",
    "parameter_bounds",
    "parameter_mae",
    "parameter_rmse",
    "relative_ptm_frobenius_error",
    "representative_parameters",
    "select_protocol",
    "trace_preservation_violation",
    "two_qubit_candidate_protocol",
    "two_qubit_parameters",
    "two_qubit_protocol",
    "unitarity",
    "unitary_channel",
    "validate_channel",
]
